---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman-demo-latest
  namespace: pacman-demo
spec:
  type: GitHub
  pathname: https://github.com/rcarrata/acm-ansible-demo.git
