apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-pr
  namespace: pacman-demo
  labels:
    app: pacman-demo
spec:
  clusterReplicas: 2
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev
