apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-app
  namespace: pacman-app
  labels:
    app: pacman-app
  annotations:
    apps.open-cluster-management.io/git-path: pacman-app/pacman
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: pacman/pacman-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-pr
