apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-demo
  namespace: pacman-demo
  labels:
    app: pacman-demo
  annotations:
    apps.open-cluster-management.io/git-path: pacman-demo/pacman
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: pacman-demo/pacman-demo-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-pr
