apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: tower-policies
spec: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: tower-resource-operator
  namespace: tower-policies
  annotations:
    apps.open-cluster-management.io/github-path: hack/manifests/policies
spec:
  type: GitHub
  pathname: https://github.com/rcarrata/acm-ansible-demo.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/github-path: tower-install/manifests/policies
  name: tower-resource-operator
  namespace: tower-policies
  labels:
    app.kubernetes.io/name: tower-resource-operator
spec:
  channel: tower-policies/tower-resource-operator
  placement:
    local: true

