apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: ansible-tower-console-link
spec:
  applicationMenu:
    imageURL: https://upload.wikimedia.org/wikipedia/commons/2/24/Ansible_logo.svg
    section: Red Hat Applications
  href: https://ansible-tower-web-svc-tower.apps.cluster-9a56.9a56.example.opentlc.com
  location: ApplicationMenu
  text: Red Hat Ansible Tower
